name: toodo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #Animation
  lottie: ^2.6.0

  #State
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf

  assets:
    - assets/lottie/
